<a href="https://colab.research.google.com/github/ulugbek-lab/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [16]:
print(pd.__version__)

2.2.3

In [5]:
mydataset = {
    'name': ["John", "Mark", "Susan","Jane", "Kike", "RURU"],
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Chevy", "MERC"],
  'counts': [3, 7, 2,4,6,2],
  'isMarried': [True, True, False, True, False, False]
}
print(mydataset)
df = pd.DataFrame(mydataset)
print(df)

{'name': ['John', 'Mark', 'Susan', 'Jane', 'Kike', 'RURU'], 'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Chevy', 'MERC'], 'counts': [3, 7, 2, 4, 6, 2], 'isMarried': [True, True, False, True, False, False]}
    name   cars  counts  isMarried
0   John    BMW       3       True
1   Mark  Volvo       7       True
2  Susan   Ford       2      False
3   Jane  Tesla       4       True
4   Kike  Chevy       6      False
5   RURU   MERC       2      False

In [6]:
df.head() # default 5 rows from top

    name   cars  counts  isMarried
0   John    BMW       3       True
1   Mark  Volvo       7       True
2  Susan   Ford       2      False
3   Jane  Tesla       4       True
4   Kike  Chevy       6      False

In [20]:
df.tail() #default 5 rows from botton

    name   cars  counts  isMarried
1   Mark  Volvo       7       True
2  Susan   Ford       2      False
3   Jane  Tesla       4       True
4   Kike  Chevy       6      False
5   RURU   MERC       2      False

In [21]:
df.shape #rows, colums

(6, 4)

In [22]:
df.columns

Index(['name', 'cars', 'counts', 'isMarried'], dtype='object')

In [23]:
df.dtypes

name         object
cars         object
counts        int64
isMarried      bool
dtype: object

In [26]:
df.describe() #numerical columns only or include = "all"

         counts
count  6.000000
mean   4.000000
std    2.097618
min    2.000000
25%    2.250000
50%    3.500000
75%    5.500000
max    7.000000

In [28]:
print(df)

    name   cars  counts  isMarried
0   John    BMW       3       True
1   Mark  Volvo       7       True
2  Susan   Ford       2      False
3   Jane  Tesla       4       True
4   Kike  Chevy       6      False
5   RURU   MERC       2      False

In [31]:
df.iloc[0:4] # select rows and its colomn

    name   cars  counts  isMarried
0   John    BMW       3       True
1   Mark  Volvo       7       True
2  Susan   Ford       2      False
3   Jane  Tesla       4       True

In [40]:
df.loc[4, "name"] #select specific row and column

'Kike'

In [45]:
print(df)

    name   cars  counts  isMarried
0   John    BMW       3       True
1   Mark  Volvo       7       True
2  Susan   Ford       2      False
3   Jane  Tesla       4       True
4   Kike  Chevy       6      False
5   RURU   MERC       2      False

In [51]:
df[df["cars"] == "MERC"] #filter data

   name  cars  counts  isMarried
5  RURU  MERC       2      False

In [53]:
df.mean(numeric_only=True) #middle number

counts       4.0
isMarried    0.5
dtype: float64

In [55]:
df.sum(numeric_only=True)#sum

counts       24
isMarried     3
dtype: int64

In [57]:
df.min()

name          Jane
cars           BMW
counts           2
isMarried    False
dtype: object

In [58]:
df.max()

name         Susan
cars         Volvo
counts           7
isMarried     True
dtype: object

In [7]:
df.median(numeric_only=True)

counts       3.5
isMarried    0.5
dtype: float64

In [8]:
df.count()

name         6
cars         6
counts       6
isMarried    6
dtype: int64

In [9]:
df.std(numeric_only=True)

counts       2.097618
isMarried    0.547723
dtype: float64

In [12]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Chevy", None],
    "counts": [None, 7,  None, 6, 2, None],
    "isMarried": [True, True, False, True, False, False]
}
df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

    cars  counts  isMarried
0    BMW     NaN       True
1  Volvo     7.0       True
2   None     NaN      False
3  Tesla     6.0       True
4  Chevy     2.0      False
5   None     NaN      False

In [14]:
df_missing.isnull().sum()

cars         2
counts       3
isMarried    0
dtype: int64

In [16]:
df_missing.dropna(how="all")
print(df_missing)

    cars  counts  isMarried
0    BMW     NaN       True
1  Volvo     7.0       True
2   None     NaN      False
3  Tesla     6.0       True
4  Chevy     2.0      False
5   None     NaN      False

In [20]:
df_missing.dropna(subset=['cars'])

    cars  counts  isMarried
0    BMW     NaN       True
1  Volvo     7.0       True
3  Tesla     6.0       True
4  Chevy     2.0      False

In [25]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts  isMarried
0      BMW     0.0       True
1    Volvo     7.0       True
2  unknown     0.0      False
3    Tesla     6.0       True
4    Chevy     2.0      False
5  unknown     0.0      False

In [33]:
# df = pd.read_csv("Titanic-Dataset.csv")



df = pd.read_excel("test.xlsx")
df.tail()
# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [30]:
df.to_excel("test.xlsx")

In [36]:
# series => 1D
cars = pd.Series(["BMW", "TESLA","FERRARI"])
print(cars)

0        BMW
1      TESLA
2    FERRARI
dtype: object

In [37]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Chevy', None]